# Generated by Django 5.1.6 on 2025-02-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Y', 'Done'), ('N', 'Not Done Yet')], default='N', max_length=1),
        ),
    ]
