# Generated by Django 5.1.6 on 2025-02-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Not Done Yet', 'Not Done Yet')], default='Not Done Yet', max_length=255),
        ),
    ]
