# Generated by Django 5.1.6 on 2025-02-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='type',
            field=models.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('Not Urgent', 'Not Urgent'), ('For Weekend', 'For Weekend'), ('Before Week Start', 'Before Week Start')], max_length=255, null=True),
        ),
    ]
