# Generated by Django 5.1.6 on 2025-02-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_todo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a document', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_img',
            field=models.ImageField(blank=True, help_text='Upload an image', null=True, upload_to='images/'),
        ),
    ]
