# Generated by Django 5.1.6 on 2025-03-28 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_alter_history_created_at_alter_history_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='file_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_dashboard.pdffile'),
        ),
        migrations.AlterField(
            model_name='history',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
